name : ProjectUnknownCurse_Actions
on:
  push: {branches: [ApprovedBuild]}

env:
  UNITY_LICENSE: ${{secrets.UNITY_LICENSE}}

jobs:
  build:
    #checkout
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
        
        #cache
      - uses: actions/cache@v1.1.0
        with:
            path: Library
            key: Library
        
      #test
      - name: Run Tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
            unityVersion: 2019.3.15f1
      #Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2019.3.15f1
          targetPlatform: Windows
      #Output
      - uses: action/upload-artifact@v1
        with:
          name: Build
          path: build   

